"""create crypto_prices table

Revision ID: 79b9b615f9ef
Revises: 
Create Date: 2025-09-28 12:27:45.318754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b9b615f9ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_prices_date'), table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_id'), table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_symbol'), table_name='crypto_prices')
    op.drop_table('crypto_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_prices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_prices_symbol'), 'crypto_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_crypto_prices_id'), 'crypto_prices', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_prices_date'), 'crypto_prices', ['date'], unique=False)
    # ### end Alembic commands ###
